---
# Copyright 2017-Present, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: SSH restart
  service:
    name: ssh
    state: restarted

- name: cpufrequtils restart
  service:
    name: cpufrequtils
    state: restarted

- name: multipath-tools restart
  service:
    name: multipath-tools
    state: restarted

- name: restart sysfs
  service:
    name: sysfsutils
    state: restarted

- name: systemd reload
  command: systemctl daemon-reload

- name: update grub
  command: /usr/sbin/update-grub2

- name: Restart BIND
  service:
    name: bind9
    state: restarted

- name: reload Consul
  systemd:
    name: consul
    state: reloaded

- name: restart iscsid
  service:
    name: iscsid
    state: restarted

- name: Restart Masakari HostMonitor
  service:
    name: masakari-hostmonitor
    state: restarted

- name: Restart Masakari IntrospectionMonitor
  service:
    name: masakari-introspectiveinstancemonitor 
    state: restarted

- name: generate auditd rules
  become: yes
  command: augenrules --load

- name: restart auditd (non RHEL)
  become: yes
  service:
    name: auditd
    state: restarted
  when: ansible_distribution_file_variety != "RedHat"

- name: stop auditd (RHEL)
  become: yes
  command: service auditd stop
  when: ansible_distribution_file_variety == "RedHat"


- name: start auditd (RHEL)
  become: yes
  command: service auditd start
  when: ansible_distribution_file_variety == "RedHat"

- name: restart splunk
  become: yes
  systemd:
     name: SplunkForwarder
     state: restarted
