---
# Copyright 2018-Present, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add Dell Repo keys
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.id }}"
    state: "{{ item.state }}"
  with_items: "{{ ops_dell_tools_apt_repo_keys }}"
  register: add_keys
  when:
    - ansible_os_family == 'Debian'
    - ansible_system_vendor == "Dell Inc."
  until: add_keys is success
  ignore_errors: True
  retries: 2
  delay: 2

- name: Add Dell OpenManage repo
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    filename: "{{ item.filename | default(omit) }}"
  with_items: "{{ ops_dell_tools_apt_repos }}"
  register: add_repos
  when:
    - ansible_os_family == 'Debian'
    - ansible_system_vendor == "Dell Inc."
  until: add_repos is success
  retries: 2
  delay: 2

- name: Update apt if necessary
  apt:
    update_cache: yes
    cache_valid_time: 600
  when:
    - add_repos is changed
    - ansible_os_family == 'Debian'
  retries: 2
  delay: 2

- name: Install Dell OpenManage packages
  apt:
    pkg: "{{ ops_dell_tools_monitoring_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
    force: yes
  when:
    - ansible_os_family == 'Debian'
    - ansible_system_vendor == "Dell Inc."
  register: support_package_installs
  until: support_package_installs is success
  retries: 2
  delay: 10

- name: Register OMSA version
  shell: |
    /opt/dell/srvadmin/bin/omreport about |awk -F': ' '/Version.*/ {str=$2; gsub("\\.","",str); print str }'
  register: omsa_version
  when: support_package_installs is success
  retries: 2
  delay: 10

- name: Start Dell dataeng service
  service:
    name: dataeng
    enabled: yes
  ignore_errors: yes
  when:
    - ansible_os_family == 'Debian'
    - ansible_system_vendor == "Dell Inc."
    - omsa_version.stdout < '1000'
  retries: 2
  delay: 2

- name: Start Dell dsm_om_connsvc service
  service:
    name: dsm_om_connsvc.service
    enabled: yes
  ignore_errors: yes
  when:
    - ansible_os_family == 'Debian'
    - ansible_system_vendor == "Dell Inc."
    - omsa_version.stdout >= '1000'
  retries: 2
  delay: 2

- name: Start Dell dsm_sa_snmpd service
  service:
    name: dsm_om_connsvc.service
    enabled: yes
  ignore_errors: yes
  when:
    - ansible_os_family == 'Debian'
    - ansible_system_vendor == "Dell Inc."
    - omsa_version.stdout >= '1000'
  retries: 2
  delay: 2
