---
# Copyright 2017-Present, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- import_playbook: "common-playbooks/register-openstack-release.yml"

- import_playbook: "common-playbooks/install-dependencies.yml"
  vars:
    host_group: "localhost"

- name: OpenStack image setup
  hosts: localhost
  environment: "{{ deployment_environment_variables | default({}) }}"
  gather_facts: "{{ gather_facts | default(true) }}"
  tasks:
    - name: Download system image file
      get_url:
        url: "{{ item.url }}"
        dest: "/var/tmp/os_image_{{ item.name }}"
        timeout: 1200
      with_items: "{{ openstack_images }}"
      when: ops_import_glance_images |default(true) |bool

    - name: Install system image
      vars:
        ansible_python_interpreter: "{{ ops_venv }}/bin/python"
      os_image:
        endpoint_type: internal
        cloud: default
        state: present
        is_public: true
        name: "{{ item.name }}"
        filename: "/var/tmp/os_image_{{ item.name }}"
        disk_format: "{{ item.format }}"
        properties: "{{ item.properties | default(omit) }}"
      with_items: "{{ openstack_images }}"
      when: ops_import_glance_images |default(true) |bool

    - name: Clean up temp file
      file:
        dest: "/var/tmp/os_image_{{ item.name }}"
        state: absent
      with_items: "{{ openstack_images }}"
      when: ops_import_glance_images |default(true) |bool

  vars_files:
    - "vars/main.yml"
    - "vars/openstack-service-config.yml"

  tags:
    - glance-image-upload

