---
# Copyright 2017-Present, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- import_playbook: "common-playbooks/register-openstack-release.yml"

- import_playbook: "common-playbooks/install-dependencies.yml"
  vars:
    host_group: "hosts:osds:mons"

- name: Install HP server monitoring
  hosts: hosts:osds:mons
  gather_facts: "{{ gather_facts | default(true) }}"
  environment: "{{ deployment_environment_variables | default({}) }}"
  pre_tasks:
    - name: Remove outdated MCP repo
      file:
        path: "/etc/apt/sources.list.d/{{ item }}"
        state: absent
      with_items:
        - downloads_linux_hpe_com_SDR_repo_mcp_ubuntu.list
        - downloads_linux_hpe_com_SDR_repo_mcp.list
        - linux.hp.com.sources.list
        - mcp.list
        - hp-mcp.list
        - hp-stk.list
      ignore_errors: True
      when:
        - ansible_os_family == 'Debian'
        - "(ansible_system_vendor == 'HP' or ansible_system_vendor == 'HPE')"
      retries: 2
  tasks:
    - include: "common-tasks/install-hp-tools.yml"
  handlers:
    - include: "handlers/main.yml"
  vars_files:
    - "vars/main.yml"
    - "vars/hp-hardware-monitoring.yml"
  vars:
    - package_install_state: "latest"
